matrix:
- name: Markdown
  sources:
  - '_site/**/*.html'
  default_encoding: utf-8
  aspell:
    lang: en
    d: en_US
  dictionary:
    wordlists:
    - .github/knownwords.txt
    encoding: utf-8
  pipeline:
  - pyspelling.filters.url:
  - pyspelling.filters.html:
      comments: false
      ignores:
      - code
      - pre
      - div.author-date
