matrix:
- name: Markdown
  sources:
  - 'site/**/*.md'
  - 'site/**/*.html'
  - 'site/**/*.adoc'
  default_encoding: utf-8
  aspell:
    lang: en
    d: en_US
  dictionary:
    wordlists:
    - .github/wordlist.txt
    encoding: utf-8
  pipeline:
  - pyspelling.filters.markdown:
  - pyspelling.filters.html:
      comments: false
      ignores:
      - code
      - pre
