files:
  - AuditLog
  - Lambda
  - Webhook
  - APIKey
  - Application
  - domain.Consent # pick up other consent objects w/o prefix
  - Form
  - FormField
  - Group
  - domain.Key # without the prefix, matches other objects containing Key
  - EventLog
  - GenericConnectorConfiguration
  - LDAPConnectorConfiguration


# thorny cases
# - UserConsent
# 2 issues. The doc lives in the Consents doc. And it has a consent object. We don't want to crawl that object, but if we exclude it when we crawl UserConsent, we exclude it when we crawl Consent as well. Need to be more sophisticated about if we should crawl.
# - Reactor
# doesn't appear to follow the pattern
