name: deploy_website

# Controls when the action will run. 
on:
  # Triggers the workflow on push or pull request events but only for the master branch
  push:
    branches: [ master ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "deploy_website"
  deploy_website:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2
      - uses: actions/setup-java@v2
        with:
          distribution: 'adopt'
          java-version: '8'
      - uses: ruby/setup-ruby@v1
        with:
          bundler-cache: true # runs 'bundle install' and caches installed gems automatically
      # makes s3_website available to savant
      - run: echo "vendor/bundle" >> $GITHUB_PATH
      # Runs a set of commands using the runners shell
      - env:
          SAVANT_REPOSITORY_PASSWORD: ${{ secrets.SAVANT_REPOSITORY_PASSWORD }}
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID}}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          ALGOLIA_API_KEY: ${{ secrets.ALGOLIA_API_KEY }}
          PATH:
        run: |
          .github/scripts/setup.sh
          bundle exec jekyll build || true # have to do this first or we miss files and the savant push barfs. 
          sleep 1
          echo $PATH
          ~/dev/savant/current/bin/sb push --debug
        shell: bash {0}
