# This is workflow for spell checking using PySpelling lib (https://pypi.org/project/pyspelling/)
name: Spellcheck
# Controls when the action will run.
on: 
  schedule:
    - cron: '31 17 * * *'
  # can run on push too, but takes too long right now
  #push:
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch: 
# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest
    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      - uses: actions/checkout@v2
      - uses: ruby/setup-ruby@v1
        with:
          bundler-cache: true # runs 'bundle install' and caches installed gems automatically
      - name: Build website for spellcheck
        run: |
          bundle exec jekyll build || true 
        shell: bash
      # Spellcheck
      - uses: igsekor/pyspelling-any@v0.0.2
        name: Spellcheck
